// Repo-doc content rendering (#3000/#3004, part of the repo-doc generation roadmap #2993). Turns a `RepoProfile`
// (src/review/repo-profile.ts) into the markdown body of a generated AGENTS.md, wrapped in a start/end marker
// pair (src/review/generated-doc-refresh.ts) so a refresh can recompute just this section and leave anything a
// maintainer added outside it untouched. Pure and deterministic: no GitHub calls, no AI -- and deliberately no
// embedded wall-clock timestamp, since that would make the SAME profile render different content on every call
// and defeat the refresh module's byte-for-byte "did anything actually change" comparison (#3004). The
// PR-delivery module (src/github/repo-doc-pr.ts) owns everything about HOW the rendered content reaches a repo.
//
// FAILS CLOSED WITH THE PROFILE: a `present: false` profile (no RAG index yet) renders nothing (`null`), mirroring
// #2999's own fail-closed design -- there is no partial or placeholder AGENTS.md, only a real one or none at all.
import type { RepoProfile, RepoProfileCommands, RepoProfileFileNamingStyle, RepoProfileTestFileConvention } from "./repo-profile";
import type { GeneratedDocMarkers } from "./generated-doc-refresh";

/** Bumped whenever the RENDERED CONTENT's structure changes in a way #3004's diff-aware refresh needs to know
 *  about (new section, reordered section, changed marker) -- not on copy-only wording tweaks. */
export const REPO_DOC_TEMPLATE_VERSION = 2;

/** HTML-comment marker pair bracketing the machine-generated section of every AGENTS.md this engine writes.
 *  Content outside this pair (added by a maintainer before the start marker or after the end marker) is treated
 *  as permanently manual and is never touched by a refresh (#3004) -- see generated-doc-refresh.ts. */
export const REPO_DOC_MARKER_START = "<!-- gittensory-repo-doc:start -->";
export const REPO_DOC_MARKER_END = "<!-- gittensory-repo-doc:end -->";
export const REPO_DOC_MARKERS: GeneratedDocMarkers = { start: REPO_DOC_MARKER_START, end: REPO_DOC_MARKER_END };

const MAX_RENDERED_TOP_LEVEL_DIRECTORIES = 12;

const FILE_NAMING_STYLE_LABELS: Record<RepoProfileFileNamingStyle, string> = {
  "kebab-case": "kebab-case (`my-file.ts`)",
  camelCase: "camelCase (`myFile.ts`)",
  snake_case: "snake_case (`my_file.ts`)",
  PascalCase: "PascalCase (`MyFile.ts`)",
  mixed: "mixed -- no single dominant style detected",
  unknown: "not detected",
};

const TEST_FILE_CONVENTION_LABELS: Record<RepoProfileTestFileConvention, string> = {
  "dot-test-suffix": "`*.test.*` files",
  "dot-spec-suffix": "`*.spec.*` files",
  "tests-directory": "a `tests/`/`__tests__/` directory",
  "none-detected": "not detected",
};

function renderCommandList(label: string, commands: string[], packageManager: RepoProfileCommands["packageManager"]): string {
  if (commands.length === 0) return `- ${label}: none detected`;
  const runner = packageManager ?? "npm";
  const items = commands.map((name) => `\`${runner} run ${name}\``).join(", ");
  return `- ${label}: ${items}`;
}

function renderTopLevelDirectories(profile: Extract<RepoProfile, { present: true }>): string {
  const entries = profile.architecture.topLevelDirectories.slice(0, MAX_RENDERED_TOP_LEVEL_DIRECTORIES);
  const lines = entries.map((entry) => `- \`${entry.path}\` -- ${entry.fileCount} file${entry.fileCount === 1 ? "" : "s"}`);
  const omitted = profile.architecture.topLevelDirectories.length - entries.length;
  if (omitted > 0) lines.push(`- (${omitted} more, not shown)`);
  return lines.join("\n");
}

function renderCiWorkflowFiles(ciWorkflowFiles: string[]): string {
  if (ciWorkflowFiles.length === 0) return "- none indexed";
  return ciWorkflowFiles.map((path) => `- \`${path}\``).join("\n");
}

/**
 * Render the markdown body of a generated AGENTS.md from a repo profile, or `null` when the profile has no data
 * (`present: false`) -- callers must treat `null` as "do not generate", not as an empty-but-valid document. The
 * ENTIRE return value is the machine-generated section: it both starts and ends with the marker pair
 * (`REPO_DOC_MARKERS`), so on a first-run file this IS the whole document, and on a refresh
 * (src/review/generated-doc-refresh.ts) it is exactly the span that gets recomputed -- anything a maintainer
 * adds before the start marker or after the end marker in the delivered file is never part of this output and
 * is therefore never touched.
 */
export function renderRepoDocContent(profile: RepoProfile): string | null {
  if (!profile.present) return null;
  const { architecture, conventions, commands, contributionWorkflow } = profile;
  return `${REPO_DOC_MARKER_START}
# AGENTS.md

This file is generated by [Gittensory](https://gittensory.aethereal.dev) from a profile of this repository's own
code -- it is not hand-written and not a generic template. Content between the markers above and below this
line is recomputed on every refresh; add anything you want kept forever outside them instead.

## Architecture

${architecture.indexedFileCount} indexed source file${architecture.indexedFileCount === 1 ? "" : "s"} across ${architecture.topLevelDirectories.length} top-level director${architecture.topLevelDirectories.length === 1 ? "y" : "ies"}:

${renderTopLevelDirectories(profile)}

## Conventions

- File naming: ${FILE_NAMING_STYLE_LABELS[conventions.fileNamingStyle]}
- Test files: ${TEST_FILE_CONVENTION_LABELS[conventions.testFileConvention]}

## Commands

- Package manager: ${commands.packageManager ?? "not detected"}
${renderCommandList("Build", commands.buildCommands, commands.packageManager)}
${renderCommandList("Test", commands.testCommands, commands.packageManager)}
${renderCommandList("Lint", commands.lintCommands, commands.packageManager)}

## Contribution workflow

- CI publishes a required check: ${contributionWorkflow.gatePublishesCheck ? "yes" : "no"}
- Linked-issue policy: ${contributionWorkflow.linkedIssuePolicy}
- Requires a linked issue: ${contributionWorkflow.requireLinkedIssue ? "yes" : "no"}
- CI workflow files:

${renderCiWorkflowFiles(contributionWorkflow.ciWorkflowFiles)}

---

Generated by Gittensory from this repository's own indexed code.
${REPO_DOC_MARKER_END}
`;
}
