import { createFileRoute, notFound } from "@tanstack/react-router";
import { Suspense } from "react";

import { DocsPage } from "@/components/site/docs-page";
import { docsClientLoader } from "@/lib/docs-client-loader";

// Rendered from content/docs/ams-env-reference.mdx via fumadocs-mdx's browser entry
// (docsClientLoader), through the existing DocsPage/Callout/CodeBlock primitives --
// not fumadocs-ui's bundled components. See docs-source.ts's comment for why the
// loader below resolves only a plain, serializable path string. The .mdx content
// itself imports AMS_ENV_REFERENCE_MARKDOWN from @/lib/ams-env-reference (generated by
// packages/loopover-miner/scripts/generate-env-reference.mjs, drift-checked in CI),
// the same pattern docs.self-hosting-configuration.tsx uses for
// SELFHOST_ENV_REFERENCE_MARKDOWN.
export const Route = createFileRoute("/docs/ams-env-reference")({
  loader: async () => {
    const { docsSource } = await import("@/lib/docs-source");
    const page = docsSource.getPage(["ams-env-reference"]);
    if (!page) throw notFound();
    return { path: page.path, title: page.data.title, description: page.data.description };
  },
  head: () => ({
    meta: [
      { title: "AMS environment variable reference — LoopOver docs" },
      {
        name: "description",
        content:
          "Every LOOPOVER_MINER_* / MINER_* env var the miner reads, where it's first referenced in code, and its default -- generated from source, never hand-copied.",
      },
      { property: "og:title", content: "AMS environment variable reference — LoopOver docs" },
      {
        property: "og:description",
        content:
          "Every LOOPOVER_MINER_* / MINER_* env var the miner reads, where it's first referenced in code, and its default -- generated from source, never hand-copied.",
      },
      { property: "og:url", content: "/docs/ams-env-reference" },
    ],
    links: [{ rel: "canonical", href: "/docs/ams-env-reference" }],
  }),
  component: AmsEnvReference,
});

function AmsEnvReference() {
  const { path, title, description } = Route.useLoaderData();
  const Content = docsClientLoader.getComponent(path);
  return (
    <DocsPage eyebrow="Maintainers" title={title} description={description}>
      <Suspense fallback={<p className="text-token-sm text-muted-foreground">Loading…</p>}>
        <Content />
      </Suspense>
    </DocsPage>
  );
}
