import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  collectMinerEnvVars,
  isMinerEnvVar,
  renderMinerEnvReferenceMarkdown,
  renderMinerEnvReferenceModule,
  writeMinerEnvReference,
  writeMinerEnvReferenceModule,
} from "../../packages/loopover-miner/scripts/generate-env-reference.mjs";

function fixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "gt-miner-env-reference-"));
  mkdirSync(join(root, "packages", "loopover-miner", "lib"), { recursive: true });
  writeFileSync(
    join(root, "packages", "loopover-miner", "lib", "a.js"),
    [
      "export function readEnv(env = process.env) {",
      "  const ignored = process.env.OTHER_APP_VAR;",
      "  const config = env.LOOPOVER_MINER_CONFIG_DIR ?? '';",
      "  const provider = env.MINER_CODING_AGENT_PROVIDER ?? '';",
      "  return resolveLocalStoreDbPath('state.sqlite3', 'LOOPOVER_MINER_RUN_STATE_DB', env);",
      "}",
      "",
    ].join("\n"),
  );
  writeFileSync(
    join(root, "packages", "loopover-miner", "lib", "b.js"),
    [
      "export function duplicate(env = process.env) {",
      "  return env.LOOPOVER_MINER_CONFIG_DIR;",
      "}",
      "",
    ].join("\n"),
  );
  return root;
}

describe("generate-env-reference (#5179)", () => {
  it("filters to LOOPOVER_MINER_* and MINER_* vars only", () => {
    expect(isMinerEnvVar("LOOPOVER_MINER_CONFIG_DIR")).toBe(true);
    expect(isMinerEnvVar("MINER_CODING_AGENT_PROVIDER")).toBe(true);
    expect(isMinerEnvVar("OTHER_APP_VAR")).toBe(false);
  });

  it("extracts static env reads, resolveLocalStoreDbPath names, and first references", () => {
    expect(collectMinerEnvVars({ rootDir: fixtureRoot() })).toEqual([
      {
        name: "LOOPOVER_MINER_CONFIG_DIR",
        firstReference: "lib/a.js",
        defaultValue: "",
      },
      {
        name: "LOOPOVER_MINER_RUN_STATE_DB",
        firstReference: "lib/a.js",
        defaultValue: null,
      },
      {
        name: "MINER_CODING_AGENT_PROVIDER",
        firstReference: "lib/a.js",
        defaultValue: "",
      },
    ]);
  });

  it("renders a deterministic markdown table with names, references, and defaults", () => {
    expect(
      renderMinerEnvReferenceMarkdown([
        { name: "LOOPOVER_MINER_CONFIG_DIR", firstReference: "lib/a.js", defaultValue: "" },
        { name: "LOOPOVER_MINER_RUN_STATE_DB", firstReference: "lib/run-state.js", defaultValue: null },
      ]),
    ).toBe(
      [
        "# loopover-miner environment variable reference",
        "",
        "Generated by `npm run miner:env-reference`. Do not edit manually.",
        "",
        "| Name | First reference | Default |",
        "| --- | --- | --- |",
        "| `LOOPOVER_MINER_CONFIG_DIR` | `lib/a.js` | `\"\"` |",
        "| `LOOPOVER_MINER_RUN_STATE_DB` | `lib/run-state.js` | (none) |",
        "",
      ].join("\n"),
    );
  });

  it("writes the generated doc and reports stale output in check mode", () => {
    const root = fixtureRoot();
    const outputPath = "packages/loopover-miner/docs/env-reference.md";
    const outputAbs = join(root, outputPath);

    const written = writeMinerEnvReference({ rootDir: root, outputPath });
    expect(written.changed).toBe(true);
    expect(existsSync(outputAbs)).toBe(true);
    const generated = readFileSync(outputAbs, "utf8");
    expect(generated).toContain("LOOPOVER_MINER_CONFIG_DIR");

    expect(writeMinerEnvReference({ rootDir: root, outputPath, check: true }).changed).toBe(false);

    writeFileSync(outputAbs, "stale\n");
    const stale = writeMinerEnvReference({ rootDir: root, outputPath, check: true });
    expect(stale.changed).toBe(true);
    expect(readFileSync(outputAbs, "utf8")).toBe("stale\n");

    const rewritten = writeMinerEnvReference({ rootDir: root, outputPath });
    expect(rewritten.changed).toBe(true);
    expect(readFileSync(outputAbs, "utf8")).toBe(generated);
  });

  it("REGRESSION: output is byte-for-byte deterministic across two runs on an unchanged tree", () => {
    const root = fixtureRoot();
    const outputPath = "packages/loopover-miner/docs/env-reference.md";
    writeMinerEnvReference({ rootDir: root, outputPath });
    const first = readFileSync(join(root, outputPath), "utf8");
    writeMinerEnvReference({ rootDir: root, outputPath });
    const second = readFileSync(join(root, outputPath), "utf8");
    expect(second).toBe(first);
  });

  it("renders a generated TS module with a typed rows array and a joined markdown constant (#6028)", () => {
    const output = renderMinerEnvReferenceModule([
      { name: "LOOPOVER_MINER_CONFIG_DIR", firstReference: "lib/a.js", defaultValue: "" },
      { name: "LOOPOVER_MINER_RUN_STATE_DB", firstReference: "lib/run-state.js", defaultValue: null },
    ]);
    expect(output).toContain("export const AMS_ENV_REFERENCE_ROWS");
    expect(output).toContain("export const AMS_ENV_REFERENCE_MARKDOWN");
    expect(output).toContain('name: "LOOPOVER_MINER_CONFIG_DIR"');
    expect(output).toContain('defaultValue: ""');
    expect(output).toContain("defaultValue: null");
    expect(output).toContain("# loopover-miner environment variable reference");
  });

  it("REGRESSION: quotes a generated markdown line with single quotes when it contains embedded double quotes, matching Prettier's own singleQuote:false-but-fewer-escapes preference (#6028)", () => {
    // The rendered markdown table cell for a quoted string default (`""`, `"production"`, ...)
    // embeds literal " characters in the line -- JSON.stringify would always double-quote the JS
    // string literal and escape those, which Prettier then reformats to single quotes to avoid the
    // escaping. Generating single-quoted output directly keeps the generator's own output already
    // Prettier-clean instead of depending on a separate --fix pass that a fresh `npm run
    // miner:env-reference` would immediately undo.
    const output = renderMinerEnvReferenceModule([
      { name: "LOOPOVER_MINER_SENTRY_ENVIRONMENT", firstReference: "lib/sentry.js", defaultValue: "production" },
    ]);
    expect(output).toContain(
      "  '| `LOOPOVER_MINER_SENTRY_ENVIRONMENT` | `lib/sentry.js` | `\"production\"` |',",
    );
    expect(output).not.toMatch(/"\| `LOOPOVER_MINER_SENTRY_ENVIRONMENT`/);
  });

  it("writes the generated TS module and reports stale output in check mode (#6028)", () => {
    const root = fixtureRoot();
    const outputPath = "apps/loopover-ui/src/lib/ams-env-reference.ts";
    const outputAbs = join(root, outputPath);

    const written = writeMinerEnvReferenceModule({ rootDir: root, outputPath });
    expect(written.changed).toBe(true);
    expect(existsSync(outputAbs)).toBe(true);
    const generated = readFileSync(outputAbs, "utf8");
    expect(generated).toContain("AMS_ENV_REFERENCE_MARKDOWN");
    expect(generated).toContain("LOOPOVER_MINER_CONFIG_DIR");

    expect(writeMinerEnvReferenceModule({ rootDir: root, outputPath, check: true }).changed).toBe(false);

    writeFileSync(outputAbs, "stale\n");
    const stale = writeMinerEnvReferenceModule({ rootDir: root, outputPath, check: true });
    expect(stale.changed).toBe(true);
    expect(readFileSync(outputAbs, "utf8")).toBe("stale\n");

    const rewritten = writeMinerEnvReferenceModule({ rootDir: root, outputPath });
    expect(rewritten.changed).toBe(true);
    expect(readFileSync(outputAbs, "utf8")).toBe(generated);
  });

  it("REGRESSION: TS module output is byte-for-byte deterministic across two runs (#6028)", () => {
    const root = fixtureRoot();
    const outputPath = "apps/loopover-ui/src/lib/ams-env-reference.ts";
    writeMinerEnvReferenceModule({ rootDir: root, outputPath });
    const first = readFileSync(join(root, outputPath), "utf8");
    writeMinerEnvReferenceModule({ rootDir: root, outputPath });
    const second = readFileSync(join(root, outputPath), "utf8");
    expect(second).toBe(first);
  });
});
